eStore\UserBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    # fields:
    #     name:
    #         type: string
    #         length: '50'
    #     email:
    #         type: string
    #         length: '100'

    oneToMany:
        posts:
            targetEntity: eStore\BlogBundle\Entity\Post
            mappedBy: user

    oneToOne:
        shoppingcart:
            targetEntity: eStore\StoreBundle\Entity\ShoppingCart
            mappedBy: user


    lifecycleCallbacks: {  }
