e_store_blog_homepage:
    path:     /
    defaults: { _controller: eStoreBlogBundle:Default:index }

e_store_blog_login:
    path: /login
    defaults: {_controller: eStoreBlogBundle:Default:login}

e_store_blog_new_post:
    path: /post/new
    defaults: { _controller: eStoreBlogBundle:Blog:new }