parameters:
#    e_store_blog.example.class: eStore\BlogBundle\Example

services:
#    e_store_blog.example:
#        class: %e_store_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
