parameters:
#    e_store_user.example.class: eStore\UserBundle\Example

services:
#    e_store_user.example:
#        class: %e_store_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
