parameters:
#    e_store_store.example.class: eStore\StoreBundle\Example

services:
#    e_store_store.example:
#        class: %e_store_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
